name: Chameleonic Tools
title: Chameleonic Title
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
description: Chameleonic web description
show_downloads: false
google_analytics:
theme: jekyll-theme-slate